# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e9b92fe2cbbfb91796e486a1aa1aa826472ece1bbd7e6c7c18b66bfffe4a4dcbe3b75b8c4dd9b11fbeeae31f707eccfad00343b0895f8f61cfac6f21f80de838

test:
  secret_key_base: 745350e42a7d19eb0ba0c03e4629bd0ca29f288d3d2ca82de84b8decc56dced92bfb8c19d0bc427b18b8ae4c2d6690db567cec3da80aec8714d41ec0f48bd486

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
